{{- if .Values.service.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "butcherctl.fullname" . }}
  labels:
    {{- include "butcherctl.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "butcherctl.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "butcherctl.selectorLabels" . | nindent 8 }}
    spec:
{{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.image.pullSecrets }}
        - name: {{ $pullSecret }}
      {{- end }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
  {{- range $key, $value := .Values.extraVars }}
          - name: {{ $key }}
            value: {{ $value }}
  {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP            
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}   
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}      
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if or ( eq .Release.Namespace "production" ) (eq .Release.Namespace "approval") }}
      tolerations:
        - key: "nodes"
          operator: "Equal"
          value: "shared"
          effect: "NoSchedule"
    {{ else }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- end }}
  {{- end }}
