{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "butcherctl.serviceAccountName" . }}
  labels:
  {{- include "butcherctl.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.image.pullSecrets }}
imagePullSecrets:
  {{- range $pullSecret := .Values.image.pullSecrets }}
  - name: {{ $pullSecret }}
  {{- end }}
  {{- end }}
  {{- end -}}